[project]
name = "MRE"
version = "2025"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "textual>=3.3.0",
]

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
